name: Push to dockerhub for napptive
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker hub credentials
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ritesh1372/bangtigada:${{ github.sha }} -t ritesh1372/bangtigada:v1.1 .
      - name: Push to Docker hub
        run: docker push ritesh1372/bangtigada:${{ github.sha }} && docker push ritesh1372/bangtigada:v1.1
