name: Deploy to napptive
on: workflow_dispatch
jobs:
  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: exec playground
        uses: napptive-actions/playground-github-action@v5.0.0
        env:
          PLAYGROUND_PAT: ${{ secrets.NAPPTIVE_PAT }}
        with:
          cmd: "apps create ./custom-app.yml"
